src/shared/Button/Button.tsx, src/shared/Button/ButtonStyle.tsx, src/shared/index.ts
- add: common button for use across all pages.
- implement: responsiveness using flex.
- add: prop support for customizing button according to theme and size.
- add: 'bold' prop for controlling font boldness.
- add: 'onClick' attribute as a receivable property.
=> #5 / feat: add common button component

public/index.html, src/App.tsx, src/shared/Button/buttonTheme.ts, src/styles/GlobalStyle.tsx, src/styles/theme.ts
- set up index.html, globalstyle.tsx for global use of pretend fonts
- add new font size themes
- add new font weight thmes
=> #13 / design: global use of pretend fonts

src/modals/LoginModal/container/hooks/LoginModalFormSubmit.ts, src/modals/LoginModal/views/EmailPassword/EmailPasswordView.tsx, src/modals/SignUpModal/components/SelectBox/useSelect.ts, src/modals/SignUpModal/container/hooks/SignupModalForm.ts, src/modals/SignUpModal/container/hooks/SignupModalFormSubmit.ts, src/modals/SignUpModal/container/hooks/VerificationCode.ts, src/modals/SignUpModal/layout/SignUpLayout.tsx, src/modals/SignUpModal/state.ts, src/modals/SignUpModal/views/EmailPassword/EmailPasswordView.tsx, src/modals/SignUpModal/views/Nickname/NicknameView.tsx, src/modals/SignUpModal/views/PasswordVerification/PasswordVerificationView.tsx, src/shared/index.ts
=> #26 / refactor: switch backend endpoint

src/modals/LoginModal/container/hooks/LoginModalFormSubmit.ts, src/pages/CreatePost/CreatePost.tsx, src/pages/CreatePost/views/MapView/MapView.tsx, src/pages/CreatePost/views/MapView/style.tsx, src/pages/EditPost/EditPost.tsx, src/pages/EditPost/index.ts, src/pages/EditPost/style.tsx, src/pages/EditPost/views/EditFormView/EditFormView.tsx, src/pages/EditPost/views/EditFormView/style.tsx, src/pages/EditPost/views/index.ts, src/providers/recoil/RecoilProvider.tsx, src/router/Router.tsx, src/shared/PostModal/PostModal.tsx, src/shared/PostModal/type.ts
- change login status code
- add styles on a edit post page
- complete put request to server
- applying map Icon to mapview
- add edit modal type
=> #35 / feat: add edit post page

src/pages/MainPage/components/MainMap/MainMap.tsx, src/pages/MainPage/components/MainPosts/MainPosts.tsx
- modify code according to changed api
=> #44 / fix: modify code according to changed api

public/index.html, src/api/api.ts, src/modals/SignUpModal/state.ts, src/modals/SignUpModal/views/PasswordVerification/PasswordVerificationView.tsx, src/pages/CreatePost/CreatePost.tsx, src/pages/DetailPage/components/CompletedButton/CompletedButton.tsx, src/pages/DetailPage/components/MetooButton/MetooButton.tsx
- delete withCredential (true > false)
- fix login check logic
=> #59 / refactor: delete withCredential + fix login state check logic

src/api/detailPageApi.ts, src/pages/DetailPage/components/CompletedButton/CompletedButton.tsx, src/pages/DetailPage/views/FooterButtons/FooterButtons.tsx
###work description
- add redirect feature in modify button
=> #55 / feat: add redirect feature in modify button

src/App.tsx, src/modals/LoginModal/container/hooks/LoginModalFormSubmit.ts, src/modals/PopUpModal/PopUpModal.tsx, src/pages/DetailPage/components/MetooButton/MetooButton.tsx, src/pages/DetailPage/container/hooks/modifyData.ts, src/pages/DetailPage/views/FooterButtons/FooterButtons.tsx, src/providers/modal/ModalProvider.tsx, src/router/Router.tsx, src/shared/TokenUtils/tokenUtils.ts, src/shared/index.ts
- implement token expiration check + auto logout in browser
- enable passing additional params (postId) to modal
- enable using react-router-dom hooks in modal
=> #63, #64 / feat+refactor : add token management logic + refactor modal

src/modals/SignUpModal/idea.txt
- test for develop branch error
=> #55 / chore: test for develop branch error

src/pages/NotFoundPage/NotFoundPage.tsx, src/pages/NotFoundPage/NotFoundStyle.tsx
- add keyframes to move illust up and down
=> #71 / design: add keyframe design

src/pages/CreatePost/CreatePost.tsx, src/pages/CreatePost/state.ts, src/pages/CreatePost/views/CreateFormView/CreateFormView.tsx, src/pages/CreatePost/views/CreateFormView/style.tsx, src/pages/CreatePost/views/MapView/MapView.tsx, src/pages/CreatePost/views/MapView/style.tsx, src/pages/EditPost/EditPost.tsx, src/pages/EditPost/style.tsx, src/pages/EditPost/type.ts, src/pages/EditPost/views/EditFormView/EditFormView.tsx, src/pages/EditPost/views/EditFormView/style.tsx, src/pages/EditPost/views/EditMapView/EditMapView.tsx, src/pages/EditPost/views/EditMapView/style.tsx, src/providers/recoil/RecoilProvider.tsx
- refactor: refactoring state in create, edit page using recoil
- fix: fix initialization problems when selecting pictures
- feat: add a kakao map and features in edit page
- design: modify detail in create, edit page
=> #80 / refactor: refactoring state in create and edit page

src/api/api.ts, src/modals/LoginModal/container/hooks/LoginModalFormSubmit.ts, src/pages/CreatePost/CreatePost.tsx, src/pages/CreatePost/state.ts, src/pages/CreatePost/views/CreateFormView/CreateFormView.tsx, src/pages/CreatePost/views/CreateFormView/style.tsx, src/pages/CreatePost/views/MapView/MapView.tsx, src/pages/CreatePost/views/MapView/style.tsx, src/pages/EditPost/EditPost.tsx, src/pages/EditPost/style.tsx, src/pages/EditPost/type.ts, src/pages/EditPost/views/EditFormView/EditFormView.tsx, src/pages/EditPost/views/EditFormView/style.tsx, src/pages/EditPost/views/EditMapView/EditMapView.tsx, src/pages/EditPost/views/EditMapView/style.tsx, src/providers/recoil/RecoilProvider.tsx, src/shared/TokenUtils/tokenUtils.ts
=> #86 / refactor: remove logic related to refresh token

src/pages/CreatePost/CreatePost.tsx, src/pages/EditPost/EditPost.tsx, src/pages/EditPost/type.ts, src/pages/EditPost/views/EditFormView/EditFormView.tsx, src/pages/EditPost/views/EditMapView/EditMapView.tsx
- fix: handle create, edit post error
=> #88 / fix: handle create, edit post error

src/api/commentsApi.ts, src/api/index.ts, src/pages/DetailPage/container/DetailContainer.tsx, src/pages/DetailPage/container/hooks/comments.ts, src/pages/DetailPage/container/hooks/completed.ts, src/pages/DetailPage/container/hooks/index.ts, src/pages/DetailPage/container/hooks/metoo.ts, src/pages/DetailPage/views/Comments/CommentsView.tsx, src/pages/OAuthPages/OAuthCallbackPage.tsx, src/pages/OAuthPages/OAuthLogout.tsx, src/pages/index.ts, src/router/Router.tsx, src/shared/Toast/toast.ts, src/shared/index.ts
- create shared toast hook + apply toast hook
- refactor comments logic in detail page
- refactor to redirect to original page after kakao login
- improve variable naming clarity
=> #102 / refactor: fix detail page logic + create toast hook

src/pages/CreatePost/style.ts, src/pages/CreatePost/views/CreateFormView/CreateFormView.tsx, src/pages/CreatePost/views/CreateFormView/style.tsx, src/pages/CreatePost/views/MapView/style.tsx, src/pages/EditPost/style.tsx, src/pages/EditPost/views/EditFormView/EditFormView.tsx, src/pages/EditPost/views/EditFormView/style.tsx, src/pages/EditPost/views/EditMapView/style.tsx, src/pages/Introduction/style.tsx, src/pages/Introduction/views/FirstIllustSection/style.tsx, src/pages/Introduction/views/Footer/style.tsx, src/pages/Introduction/views/LandingView/LandingView.tsx, src/pages/Introduction/views/LandingView/style.tsx, src/pages/Introduction/views/SecondIllustSection/style.tsx, src/pages/NotFoundPage/NotFoundStyle.tsx
- design: add responsive ui using media query on create, edit, landing, 404 page
=> #104 / design: add responsive ui

src/pages/CreatePost/CreatePost.tsx, src/pages/EditPost/EditPost.tsx, src/pages/Introduction/views/FirstIllustSection/style.tsx, src/pages/Introduction/views/SecondIllustSection/style.tsx
- refactor: using common modal on create, edit page
=> #110 / refactor: using common modal

src/pages/DetailPage/views/Comments/CommentsStyle.tsx, src/pages/DetailPage/views/Comments/CommentsView.tsx, src/pages/Introduction/style.tsx, src/pages/Introduction/views/LandingView/style.tsx
- design: add responsive ui on landing page, comments
=> #115 / design: add responsive ui

src/assets/logo.ts, src/pages/CreatePost/views/MapView/style.tsx, src/pages/EditPost/views/EditMapView/style.tsx, src/pages/Introduction/style.tsx, src/pages/Introduction/views/FirstIllustSection/style.tsx, src/pages/Introduction/views/Footer/style.tsx, src/pages/Introduction/views/SecondIllustSection/style.tsx
- design: modify responsive ui detail
=> #121 / design: modify responsive ui detail 

src/pages/MainPage/components/MainModal/MainModal.tsx, src/pages/MainPage/components/MainModal/MainModalStyle.tsx, src/pages/MainPage/components/MainPost/MainPost.tsx, src/pages/MainPage/views/MainMap/MainMapStyle.tsx, src/pages/MainPage/views/MainPosts/MainPosts.tsx
=> #135 / fix: modify code after test

src/pages/CreatePost/style.ts
###work description
- design: modify style on create page
=> #139 / design: modify style on create page

src/pages/CreatePost/views/MapView/style.tsx, src/pages/EditPost/views/EditMapView/style.tsx, src/pages/Introduction/views/LandingView/style.tsx
- design: modify styles in landing, create, edit page
=> #143 / design: modify styles in landing, create, edit page

src/modals/SignUpModal/components/SelectBox/useSelect.ts
- resolve dropdown not closing bug
=> #102 / fix: resolve dropdown not closing bug

src/pages/MyPage/components/Navbar.tsx, src/pages/MyPage/components/UserPost/UserPost.tsx, src/pages/MyPage/components/UserPost/UserPostStyle.tsx, src/pages/MyPage/components/index.ts, src/pages/MyPage/container/MyPageContainer.tsx, src/pages/MyPage/layout/MyPageLayout.tsx, src/pages/MyPage/views/UserPosts/UserPostsView.tsx, src/pages/MyPage/views/UserPosts/UserPostsViewStyle.tsx, src/pages/MyPage/views/index.ts, src/styles/theme.ts
- design: add responsive post ui to my page
- design: add responsive design to my page menu to top bar
=> #152 / design: add mypage ui 

src/shared/Header/Header.tsx
- fix: modify header menu in header
=> #168 / chore: merge develop to main for deploy

src/api/api.ts, src/assets/icon.tsx, src/pages/MainPage/views/MainMap/MainMapStyle.tsx, src/pages/MyPage/components/Navbar.tsx, src/pages/MyPage/components/UserPost/UserPost.tsx, src/pages/MyPage/container/MyPageContainer.tsx, src/pages/MyPage/container/hooks/userPosts/userPostsData.ts, src/pages/MyPage/state.ts, src/pages/MyPage/views/UserPosts/UserPostsView.tsx, src/pages/MyPage/views/UserPosts/UserPostsViewStyle.tsx, src/shared/Header/Header.tsx, src/shared/Header/HeaderStyle.tsx, src/styles/MediaQueries.ts, src/styles/theme.ts, src/styles/type.ts
- feat: add my posts functionality to my page
- feat: add pagination feature
- design: add reactive size condition
=> #160 / feat: add my posts functionality to my page

src/api/api.ts, src/pages/MyPage/container/MyPageContainer.tsx, src/pages/MyPage/views/UserPosts/UserPostsView.tsx
- fix: resolved issue of slicing undefined value
=> fix: resolved issue of slicing undefined value

src/pages/MyPage/components/Navbar.tsx, src/pages/MyPage/container/MyPageContainer.tsx, src/pages/MyPage/container/hooks/userPosts/userPostsData.ts, src/pages/MyPage/state.ts, src/pages/MyPage/views/UserPosts/UserPostsView.tsx
- fix: resolve api error when logging out from my page
- fix: resolve duplicate key error
- fix: resolve page number re-rendering issue
- design: update top title based on menu selection
=> #181 / fix: resolve my page error
